nodeLinker: "pnp"
pnpMode: "strict"

packageExtensions:
  "langium@*":
    dependencies:
      "@chevrotain/regexp-to-ast": "*"
      vscode-jsonrpc: "*"
      vscode-languageserver-types: "*"
      vscode-languageserver-protocol: "*"