[build]
  command = "yarn build"

# Redirect admin to Laravel backend
[[redirects]]
  from = "/admin/*"
  to = "https://api.nickbell.dev/admin/:splat"
  status = 301
  force = true

# RSS feed proxy to backend
[[redirects]]
  from = "/feed"
  to = "https://api.nickbell.dev/feed"
  status = 200
  force = true
